### ISSUE TITLE
eef_point,tip_point,uv

### ISSUE THREAD

**Issue by easyfcn** [kaixindelele/Eye-to-Hand-Calibration#1]
您好，我想咨询一下
calibration_class.py里面用的点集，点是嗲表什么意思，什么格式，谢谢您！
eef_point,tip_point,uv
[-0.276006 -0.45498   0.304999 -0.090001 -0.045001  0.087998],[-0.66926564 -0.44122847  0.30499414],"[579, 229]"
[-0.275974 -0.455025  0.304982 -0.090005 -0.044999  0.08601 ],[-0.66851855 -0.42762012  0.30495772],"[505, 225]"
[-0.276005 -0.454994  0.305001 -0.090001 -0.045002  0.085   ],[-0.66800719 -0.42069338  0.30499614],"[469, 224]"
[-0.275999 -0.474998  0.304989 -0.090002 -0.045004  0.088004],[-0.66925991 -0.4612828   0.30497929],"[688, 226]"

**Comment by kaixindelele** [comment]
eef_point：机械臂末端xyz三维坐标，以机械臂基座为坐标原点，单位为m;
tip_point：为针尖的三维坐标，以机械臂基座为坐标原点，单位为m;
uv：为针尖在图像坐标系中的坐标，坐标原点应该是左上角，单位为像素点；

**Comment by easyfcn** [comment]
> eef_：机械臂动画坐标坐标，以机械臂坐标为坐标原点，单位m；
> tip_point：为针尖的三维坐标，以机械臂肘为坐标原点，单位为m；
> uv：为针尖在图像坐标系中的坐标，坐标原点应该是左上角，单位为像素点；
您好，感谢你的回复！我刚接触这个，我想求出像素点与真实世界点的对应矩阵，可以把eef_point去掉，只使用tip_point与tuv吗？ 您有别的好方法推荐吗？ 拜谢

**Comment by kaixindelele** [comment]
我这个基本上就是这么操作的啊，eef_point和tip_point的关系，就是一个刚性变换，量一下就行了，因此，你会有一一对应的tip_point和uv的标定点。求解一下就能拿到对应的矩阵M
